version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
        - target: 443
          published: 443
          protocol: tcp
        - target: 80
          published: 8080
          protocol: tcp
    volumes:
      - /da/tls:/etc/nginx/tls
    depends_on:
      - backend
      - frontend
      - phpmyadmin
  backend:
    init: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ../volume/backend/file:/backend/file
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD : "backend"
    volumes:
      - ../volume/mysql:/var/lib/mysql
      # - ./mysql/log:/ft
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=backend
      - PMA_PASSWORD=backend
